import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen">
          

          {/* <aside className="min-w-54 bg-red-900 text-white flex flex-col p-4">
            <h1 className="text-xl font-bold mb-6">My App</h1>

            <nav className="flex flex-col gap-2">
              <a href="/" className="hover:bg-darkRed p-2 rounded">
                Dashboard
              </a>
              <a href="/Purchase" className="hover:bg-red-400 p-2 rounded">
                Purchase
              </a>
              <a href="/Inventory" className="hover:bg-red-400 p-2 rounded">
                None
              </a>
              <a href="/Reports" className="hover:bg-red-400 p-2 rounded">
                None
              </a>
            </nav>
          </aside>

        */}
          <main className="flex-1 bg-gray-100 p-6">
            {children}
          </main>

        </div>
      </body>
    </html>
  );
}
